### ISSUE TITLE
Panic: unexpected EOF

### ISSUE THREAD

**Issue by icantnamethings** [padok-team/yatas#94]
$yantas
New version available for plugin aws : 1.4.0
panic: unexpected EOF

goroutine 1 [running]:
github.com/padok-team/yatas/plugins/commons.(*YatasRPC).Run(0x14000406008, 0x140001254a4?)
	/home/runner/work/YATAS/YATAS/plugins/commons/commons.go:23 +0xd0
github.com/padok-team/yatas/plugins/manager.RunPlugin({{0x140001254a4, 0x3}, 0x1, {0x1400013a660, 0x1f}, {0x0, 0x0}, {0x140001254d0, 0x6}, {0x1400013a780, ...}, ...}, ...)
	/home/runner/work/YATAS/YATAS/plugins/manager/manager.go:69 +0x424
github.com/padok-team/yatas/internal/cli.runChecksPlugins(0x1400018c500, 0x140001d7df0)
	/home/runner/work/YATAS/YATAS/internal/cli/cli.go:43 +0x18c
github.com/padok-team/yatas/internal/cli.Execute()
	/home/runner/work/YATAS/YATAS/internal/cli/cli.go:130 +0xe0
main.run()
	/home/runner/work/YATAS/YATAS/main.go:52 +0x88
main.main()
	/home/runner/work/YATAS/YATAS/main.go:14 +0x1c

**Comment by piaverous** [comment]
The problem causing this was in the yatas-aws plugin, which was fixed by the two following PRs : 
- https://github.com/padok-team/yatas-aws/pull/74
- https://github.com/padok-team/yatas-aws/pull/76

However, maybe we can improve error handling in `yatas` itself o be more explicit ?

**Comment by StanGirard** [comment]
Done :) Improved handling with version 1.4.0
